### ISSUE TITLE
Build failure on Foxy/Windows in moveit_chomp_optimizer_adapter

### ISSUE THREAD

**Issue by lilustga** [ros-planning/moveit2#1040] opened 2022-01-27 19:35 UTC
### Description
Unresolved symbol error for collision_detection::CollisionDetectorAllocatorHybrid::NAME. I would have expected #936 to fix this but I'm still hitting the error with these changes. I have a theory that it's specific to my system due to other binaries and am investigating.

### Your environment
* ROS Distro: Foxy
* OS Version: Windows 11
* Source build
* If source, which branch: Foxy

### Steps to reproduce
* Install ROS on Windows
* clone moveit2/foxy
* 'vcs import < moveit2.repos'
* `IGNORED_PACKAGES=warehouse_ros_mongo`
* `colcon build --packages-skip-by-dep %IGNORED_PACKAGES%  --packages-skip %IGNORED_PACKAGES% --event-handlers desktop_notification- status- --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo`

### Actual behaviour
Unresolved symbol error for collision_detection::CollisionDetectorAllocatorHybrid::NAME.

**Comment by MikeWise2718** [comment] 2022-07-28 09:49
I am hitting this now. Any resolution?

**Comment by lilustga** [comment] 2022-08-03 23:29
@MikeWise2718 From what I remember it was a red herring that was caused by a binary mismatch on my local system. It wasn't reproducible in build pipelines or other user's machines.

**Comment by henningkayser** [comment] 2023-01-26 10:52
I'm closing this since the cause has been a workspace issue. @lilustga please reopen if you think there is still something to be addressed.

**Closed by henningkayser** 2023-01-26 10:52 UTC
Labels: bug

**Comment by VinHub-Gitcent** [comment] 2023-10-17 14:58
@MikeWise2718 Do you remember how you fixed it for you? I am facing the same issue now and I don't really have an idea on where to start here.

**Comment by Haibara-z** [comment] 2023-12-04 16:28
> I am hitting this now. Any resolution?

Do you fixed it? I am hitting this now. Any resolution?
