### ISSUE TITLE
Building problem: Failed   <<< moveit_ros_planning

### ISSUE THREAD

**Issue by Llavrih** [ros-planning/moveit2#1429] opened 2022-07-14 08:47 UTC
### Description
---
I'm tying to source build moveit2 form main branch but getting error:

Starting >>> moveit_common
Starting >>> moveit_resources_panda_description
Starting >>> moveit_resources_fanuc_description
Starting >>> controller_manager_msgs
Starting >>> moveit_configs_utils
Starting >>> ros2_control_test_assets
Starting >>> moveit_resources_pr2_description
Starting >>> moveit_resources_prbt_support
Finished <<< moveit_common [0.83s]
Starting >>> joint_limits
Finished <<< moveit_resources_prbt_support [0.82s]
Starting >>> rls_6_robot_description_test
Finished <<< moveit_resources_panda_description [1.25s]
Starting >>> moveit_resources_panda_moveit_config
 stderr: moveit_configs_utils
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(

Finished <<< moveit_configs_utils [1.29s]
Finished <<< moveit_resources_fanuc_description [1.35s]
Starting >>> moveit_resources_fanuc_moveit_config
Finished <<< ros2_control_test_assets [1.40s]
Starting >>> hardware_interface
Finished <<< moveit_resources_pr2_description [1.50s]
Finished <<< moveit_resources_panda_moveit_config [0.96s]
Starting >>> moveit_core
Finished <<< moveit_resources_fanuc_moveit_config [0.95s]
Starting >>> moveit_resources
Finished <<< rls_6_robot_description_test [1.66s]
Finished <<< moveit_resources [0.96s]
[Processing: controller_manager_msgs, hardware_interface, joint_limits, moveit_core]
Finished <<< controller_manager_msgs [42.4s]
Finished <<< joint_limits [44.6s]
Finished <<< hardware_interface [1min 10s]
Starting >>> controller_interface
Starting >>> transmission_interface
[Processing: controller_interface, moveit_core, transmission_interface]
Finished <<< controller_interface [36.8s]
Starting >>> controller_manager
Finished <<< transmission_interface [45.1s]
[Processing: controller_manager, moveit_core]
[Processing: controller_manager, moveit_core]
 stderr: controller_manager
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(

Finished <<< controller_manager [1min 18s]
Starting >>> ros2controlcli
 stderr: ros2controlcli
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(

Finished <<< ros2controlcli [0.89s]
Starting >>> ros2_control
Finished <<< ros2_control [0.64s]
[Processing: moveit_core]
[Processing: moveit_core]
[Processing: moveit_core]
Finished <<< moveit_core [4min 51s]
Starting >>> moveit_ros_occupancy_map_monitor
Starting >>> moveit_simple_controller_manager
Starting >>> moveit_resources_prbt_ikfast_manipulator_plugin
Starting >>> chomp_motion_planner
Starting >>> pilz_industrial_motion_planner_testutils
[Processing: chomp_motion_planner, moveit_resources_prbt_ikfast_manipulator_plugin, moveit_ros_occupancy_map_monitor, moveit_simple_controller_manager, pilz_industrial_motion_planner_testutils]
Finished <<< moveit_simple_controller_manager [32.5s]
Starting >>> moveit_plugins
Starting >>> moveit_ros_control_interface
Finished <<< moveit_plugins [0.70s]
Finished <<< pilz_industrial_motion_planner_testutils [37.8s]
Finished <<< chomp_motion_planner [47.5s]
Starting >>> moveit_chomp_optimizer_adapter
Starting >>> moveit_planners_chomp
Finished <<< moveit_resources_prbt_ikfast_manipulator_plugin [52.4s]
Finished <<< moveit_ros_occupancy_map_monitor [57.5s]
Starting >>> moveit_ros_planning
Finished <<< moveit_chomp_optimizer_adapter [13.1s]
Finished <<< moveit_ros_control_interface [29.2s]
Finished <<< moveit_planners_chomp [26.7s]
[Processing: moveit_ros_planning]
[Processing: moveit_ros_planning]
[Processing: moveit_ros_planning]
 stderr: moveit_ros_planning
/usr/bin/ld: ../planning_scene_monitor/libmoveit_planning_scene_monitor.so.2.5.1: undefined reference to `planning_scene::PlanningScene::setAttachedBodyUpdateCallback(boost::function<void (moveit::core::AttachedBody*, bool)> const&)'
/usr/bin/ld: ../planning_scene_monitor/libmoveit_planning_scene_monitor.so.2.5.1: undefined reference to `planning_scene::PlanningScene::setCollisionObjectUpdateCallback(boost::function<void (std::shared_ptr<collision_detection::World::Object const> const&, collision_detection::World::Action)> const&)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [planning_components_tools/CMakeFiles/moveit_print_planning_scene_info.dir/build.make:318: planning_components_tools/moveit_print_planning_scene_info] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:930: planning_components_tools/CMakeFiles/moveit_print_planning_scene_info.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: ../planning_scene_monitor/libmoveit_planning_scene_monitor.so.2.5.1: undefined reference to `planning_scene::PlanningScene::setAttachedBodyUpdateCallback(boost::function<void (moveit::core::AttachedBody*, bool)> const&)'
/usr/bin/ld: ../planning_scene_monitor/libmoveit_planning_scene_monitor.so.2.5.1: undefined reference to `planning_scene::PlanningScene::setCollisionObjectUpdateCallback(boost::function<void (std::shared_ptr<collision_detection::World::Object const> const&, collision_detection::World::Action)> const&)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [planning_components_tools/CMakeFiles/moveit_evaluate_collision_checking_speed.dir/build.make:318: planning_components_tools/moveit_evaluate_collision_checking_speed] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1020: planning_components_tools/CMakeFiles/moveit_evaluate_collision_checking_speed.dir/all] Error 2
/usr/bin/ld: libmoveit_planning_scene_monitor.so.2.5.1: undefined reference to `planning_scene::PlanningScene::setCollisionObjectUpdateCallback(boost::function<void (std::shared_ptr<collision_detection::World::Object const> const&, collision_detection::World::Action)> const&)'
/usr/bin/ld: libmoveit_planning_scene_monitor.so.2.5.1: undefined reference to `planning_scene::PlanningScene::setAttachedBodyUpdateCallback(boost::function<void (moveit::core::AttachedBody*, bool)> const&)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [planning_scene_monitor/CMakeFiles/current_state_monitor_tests.dir/build.make:320: planning_scene_monitor/current_state_monitor_tests] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:788: planning_scene_monitor/CMakeFiles/current_state_monitor_tests.dir/all] Error 2
/usr/bin/ld: libmoveit_planning_scene_monitor.so.2.5.1: undefined reference to `planning_scene::PlanningScene::setCollisionObjectUpdateCallback(boost::function<void (std::shared_ptr<collision_detection::World::Object const> const&, collision_detection::World::Action)> const&)'
/usr/bin/ld: libmoveit_planning_scene_monitor.so.2.5.1: undefined reference to `planning_scene::PlanningScene::setAttachedBodyUpdateCallback(boost::function<void (moveit::core::AttachedBody*, bool)> const&)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [planning_scene_monitor/CMakeFiles/trajectory_monitor_tests.dir/build.make:320: planning_scene_monitor/trajectory_monitor_tests] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:820: planning_scene_monitor/CMakeFiles/trajectory_monitor_tests.dir/all] Error 2
/usr/bin/ld: ../planning_scene_monitor/libmoveit_planning_scene_monitor.so.2.5.1: undefined reference to `planning_scene::PlanningScene::setAttachedBodyUpdateCallback(boost::function<void (moveit::core::AttachedBody*, bool)> const&)'
/usr/bin/ld: ../planning_scene_monitor/libmoveit_planning_scene_monitor.so.2.5.1: undefined reference to `planning_scene::PlanningScene::setCollisionObjectUpdateCallback(boost::function<void (std::shared_ptr<collision_detection::World::Object const> const&, collision_detection::World::Action)> const&)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [planning_components_tools/CMakeFiles/moveit_visualize_robot_collision_volume.dir/build.make:319: planning_components_tools/moveit_visualize_robot_collision_volume] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:990: planning_components_tools/CMakeFiles/moveit_visualize_robot_collision_volume.dir/all] Error 2
/usr/bin/ld: ../planning_scene_monitor/libmoveit_planning_scene_monitor.so.2.5.1: undefined reference to `planning_scene::PlanningScene::setAttachedBodyUpdateCallback(boost::function<void (moveit::core::AttachedBody*, bool)> const&)'
/usr/bin/ld: ../planning_scene_monitor/libmoveit_planning_scene_monitor.so.2.5.1: undefined reference to `planning_scene::PlanningScene::setCollisionObjectUpdateCallback(boost::function<void (std::shared_ptr<collision_detection::World::Object const> const&, collision_detection::World::Action)> const&)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [planning_components_tools/CMakeFiles/moveit_display_random_state.dir/build.make:318: planning_components_tools/moveit_display_random_state] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:960: planning_components_tools/CMakeFiles/moveit_display_random_state.dir/all] Error 2
/usr/bin/ld: ../planning_scene_monitor/libmoveit_planning_scene_monitor.so.2.5.1: undefined reference to `planning_scene::PlanningScene::setAttachedBodyUpdateCallback(boost::function<void (moveit::core::AttachedBody*, bool)> const&)'
/usr/bin/ld: ../planning_scene_monitor/libmoveit_planning_scene_monitor.so.2.5.1: undefined reference to `planning_scene::PlanningScene::setCollisionObjectUpdateCallback(boost::function<void (std::shared_ptr<collision_detection::World::Object const> const&, collision_detection::World::Action)> const&)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [planning_components_tools/CMakeFiles/moveit_publish_scene_from_text.dir/build.make:318: planning_components_tools/moveit_publish_scene_from_text] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1050: planning_components_tools/CMakeFiles/moveit_publish_scene_from_text.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2

Failed   <<< moveit_ros_planning [1min 52s, exited with code 2]

Summary: 29 packages finished [7min 43s]
  1 package failed: moveit_ros_planning
  4 packages had stderr output: controller_manager moveit_configs_utils moveit_ros_planning ros2controlcli
  24 packages not processed

I also have a question if binary build will be ready for humble anytime soon?

### Your environment
---
* ROS Distro: Humble
* OS Version: e.g. Ubuntu 22.04
* Source build
* branch main

### Steps to reproduce
---
Following steps https://moveit.ros.org/install-moveit2/source/ for ros humble source build, using branch main (branch humble does not have right form of launch files for msa -> the pkg I want to use).

**Comment by rcywongaa** [comment] 2022-09-01 14:27
Possible duplicate of https://github.com/ros-planning/moveit2/issues/1476, make sure you have the most up to date humble branch and clean build

**Comment by henningkayser** [comment] 2023-01-25 18:25
Weeding out old issues. I'm pretty sure that this has been fixed for a while, the linked issues have been closed as well. Please reopen or comment if you think this hasn't been addressed yet.

**Closed by henningkayser** 2023-01-25 18:25 UTC
Labels: bug
