### ISSUE TITLE
Duplicate nodes in run_moveit_cpp demo

### ISSUE THREAD

**Issue by AdamPettinger** [ros-planning/moveit2#252] opened 2020-08-20 20:28 UTC
`###` Description

Running both demo launch files in `run_moveit_cpp` give duplicate nodes:
![image](https://user-images.githubusercontent.com/28165117/90821844-2bee6800-e2f9-11ea-85c9-dff062763695.png)

I believe this is caused by #230 as I can rebase to remove those commits and do not get duplicate nodes.

### Your environment
* ROS Distro: Foxy
* OS Version: Ubuntu 20.04
* Source build: master branch

### Steps to reproduce
[Build moveit2 from source](https://moveit.ros.org/install-moveit2/source/)
`ros2 launch run_moveit_cpp run_moveit_cpp.launch.py`
In a new terminal while that is running:
`ros2 node list`

### Expected behaviour
Rebasing to before that PR was merged gives what I would expect:
![Pre-PSM-PR-node-list](https://user-images.githubusercontent.com/28165117/90822204-b5059f00-e2f9-11ea-97e0-67deec3ef374.png)

**Comment by henningkayser** [comment] 2020-08-26 12:05
@AdamPettinger are you sure this is still an issue? I thought this was fixed before the referenced PR was merged. I'm not able to reproduce this.

**Comment by AdamPettinger** [comment] 2020-08-26 13:56
> Possibly useable information: a recent fix for the same kind of problem in navigation2

@mikeferguson That worked like a charm, thanks! Shamelessly copied

**Closed** 2020-08-27 13:52 UTC
Labels: bug
