### ISSUE TITLE
`moveit_configs_utils` tries to load `cartesian_limits.yaml` even if Pilz planner is not loaded

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit2#1328] opened 2022-06-08 15:58 UTC
### Description

See discussion here:  https://github.com/ros-planning/moveit2_tutorials/pull/391#issuecomment-1150096437

**Comment by henningkayser** [comment] 2023-03-10 19:52
Is there anything to do about this now? It's clearly not a bug since nothing is broken because of this. My thought is that technically we could use cartesian limits outside of PILZ in the future.

**Comment by henningkayser** [comment] 2024-02-27 11:36
Fixed by #1519

**Closed by henningkayser** 2024-02-27 11:36 UTC
Labels: question
